Contract
nikos-terzo/battle_pass pull request #1
Opened 2023-11-21 09:29 UTC by nikos-terzo

2023-11-21 12:22 UTC, siomari requested changes

2023-11-21 12:22 UTC, siomari commented on sources/battle_pass.move
> +    const EInvalidSeasonTicket: u64 = 0;
Those two error consts should be before the struct declarations

2023-11-21 12:22 UTC, siomari commented on sources/battle_pass.move
> +                sword_reward: Sword {
It would be reasonable to create a different function for mint_sword for better code readability

2023-11-21 12:22 UTC, siomari commented on sources/battle_pass.move
> +        (season_ticket, sword_reward)
SeasonTicket holds only the key trait. Can you transfer it to the user after returning it? The ticket should be transferred where it gets created.

2023-11-22 11:22 UTC, nikos-terzo commented on sources/battle_pass.move
> +                sword_reward: Sword {
The concept for this very basic example is:

> Develop a battle pass for their game, which includes NFT collectibles and dynamic NFT level-up gamification.

So I will keep it as is.

2023-11-22 11:32 UTC, nikos-terzo commented on sources/battle_pass.move
> +        (season_ticket, sword_reward)
Done

2023-11-22 11:58 UTC, siomari commented on sources/battle_pass.move
> +                sword_reward: Sword {
In a real case, the sword could be a different module, so there is a need for that case. However, as we are talking about a simple example, you can leave it as is.

2023-11-22 11:59 UTC, merged